<div class="header-replace header-position"><header class="header_bg header-wrap header-default floating-nav floating-nav-sticky"><div id="megamenuWidthBox" class="container"></div>  <div class="header-center-bg floating-dark-color header-bg-box" data-height="70"  id="headerrow-873518"><div class="container"><div class="header-center header-container-box"> <div class="header-area area-left header-vertical  pl-35 header-vertical" style="width:265px"  id="column-552682"><div class="header-content-wrap"> <div class="logo" id="logo121406"><dnn:LOGO runat="server" id="dnnLOGO121406" cssClass="header-logo floating-header-logo" BorderWidth="0" /></div></div></div> <div class="header-area area-center header-vertical text-center header-vertical text-center"   id="column-925494"><div class="header-content-wrap"> <div class="nav-bar"><div id="dng-megamenu615053" data-split="false" class="dng-megamenu hoverstyle_5 flyout-shadow mega-shadow"><dnn:MEGAMENU runat="server" id="MEGAMENU615053" Effect="Hslide" ViewLevel="0" ShowUI="Extension" WidthBoxClassName="#megamenuWidthBox"/></div></div>
	<dnn:DnnCssInclude runat="server" FilePath="resource/header/megamenu/megamenu.css" PathNameAlias="SkinPath" Priority="9"  /><dnn:DnnJsInclude runat="server" FilePath="resource/header/megamenu/megamenu.js" PathNameAlias="SkinPath" Priority="9" ForceProvider ="DnnFormBottomProvider" /></div></div> <div class="header-area area-right header-horizontal  pr-35 d-none d-xl-table-cell header-horizontal" style="width:265px"  id="column-944385"><div class="header-content-wrap"> <div class="dngTextBox"><span class="color-accent">+ Contact:</span> (845) 359-7777</div></div></div> </div></div></div>  </header></div><div class="mobile-header-replace"><header class="mobile-header floating-nav"> <div class="header-mobile-bg mobile-header-shadow" id="mobileheader-230621"><div class="header-mobile"> <div class="header-area area-left header-horizontal text-left header-horizontal text-left"   id="column-212743"><div class="header-content-wrap"> <div class="search-popup-box" id="search-popup-box346748" placeholder="Enter any key words to search"><div class="icon hover-accent"><span class="magnifier"><i></i></span></div><div class="popup-reveal color-dark "></div><div class="popup-content color-dark bg-accent"><div class="popup-close hover-accent"><span class="icon-cross"></span></div><div class="popup-center"><dnn:SEARCH runat="server" id="dnnSEARCH346748" CssClass="search"  ShowSite="False" ShowWeb="False"  submit=" " /></div></div></div>
		<dnn:DnnCssInclude runat="server" FilePath="resource/header/search-popup/search-popup.css" PathNameAlias="SkinPath" Priority="318" HtmlAttributesAsString="media:'none',title:'all',onload:'this.media=this.title"  />
		<dnn:DnnJsInclude runat="server" FilePath="resource/header/search-popup/search-popup.js"  ForceProvider ="DnnFormBottomProvider" PathNameAlias="SkinPath" Priority="9" HtmlAttributesAsString="async:'async'"   />	
		</div></div> <div class="header-area area-center header-horizontal  header-horizontal"   id="column-815836"><div class="header-content-wrap"> <div class="logo" id="logo299577"><dnn:LOGO runat="server" id="dnnLOGO299577" cssClass="header-logo" BorderWidth="0" /><dnn:LOGO runat="server" id="floatingLOGO299577" cssClass="floating-header-logo" BorderWidth="0" /></div></div></div> <div class="header-area area-right header-horizontal text-right header-horizontal text-right"   id="column-901721"><div class="header-content-wrap"> <div class="mobile-menu-icon"><span class="dg-menu-anime"><i></i></span></div>
	<div class="mobilemenu-main" id="mobilemenu693433" data-title="Menu"><span class="mobileclose"></span>
	<div class="m-menu">
	<dnn:LEFTGOMENU runat="server" id="MOBILEMENU693433" Effect="HTML"/> 
	</div>
	</div>
	<dnn:DnnCssInclude runat="server" FilePath="resource/header/mobilemenu/mobilemenu.css" PathNameAlias="SkinPath" Priority="317" HtmlAttributesAsString="media:'none',title:'all',onload:'this.media=this.title"  />
	<dnn:DnnJsInclude runat="server" FilePath="resource/header/mobilemenu/mobilemenu.js" ForceProvider ="DnnFormBottomProvider" PathNameAlias="SkinPath" Priority="17" HtmlAttributesAsString="async:'async'"   />	
	</div></div> </div></div> </header></div>