<div class="header-replace header-position"><header class="header_bg header-wrap header-default floating-nav floating-nav-sticky"><div id="megamenuWidthBox" class="container"></div>  <div class="header-center-bg floating-dark-color header-bg-box" data-height="70"  id="headerrow-950180"><div class="container"><div class="header-center header-container-box"> <div class="header-area area-left header-vertical  pl-35 header-vertical" style="width:155px"  id="column-16184"><div class="header-content-wrap"> <div class="logo" id="logo164259"><dnn:LOGO runat="server" id="dnnLOGO164259" cssClass="header-logo floating-header-logo" BorderWidth="0" /></div></div></div> <div class="header-area area-center header-vertical text-center header-vertical text-center"   id="column-77633"><div class="header-content-wrap"> <div class="nav-bar"><div id="dng-megamenu993511" data-split="false" class="dng-megamenu hoverstyle_3 flyout-shadow mega-shadow"><dnn:MEGAMENU runat="server" id="MEGAMENU993511" Effect="Hslide" ViewLevel="0" ShowUI="Extension" WidthBoxClassName="#megamenuWidthBox"/></div></div>
	<dnn:DnnCssInclude runat="server" FilePath="resource/header/megamenu/megamenu.css" PathNameAlias="SkinPath" Priority="9"  /><dnn:DnnJsInclude runat="server" FilePath="resource/header/megamenu/megamenu.js" PathNameAlias="SkinPath" Priority="9" ForceProvider ="DnnFormBottomProvider" /></div></div> <div class="header-area area-right header-horizontal  pr-35 header-horizontal" style="width:70px"  id="column-992062"><div class="header-content-wrap"> <div class="dngTextBox"><a href="https://www.dnngo.net/DNNStore/tabid/58/ProductID/1653/Default.aspx" target="_blank" class="homepage10-header-btn box-shadow bg-accent3" title="Buy It Now">BUY IT NOW</a></div></div></div> </div></div></div>  </header></div><div class="mobile-header-replace"><header class="mobile-header floating-nav"> <div class="header-mobile-bg mobile-header-shadow" id="mobileheader-547853"><div class="header-mobile"> <div class="header-area area-left header-horizontal text-left header-horizontal text-left"   id="column-83280"><div class="header-content-wrap"> <div class="search-popup-box" id="search-popup-box427525" placeholder="Enter any key words to search"><div class="icon hover-accent"><span class="magnifier"><i></i></span></div><div class="popup-reveal color-dark "></div><div class="popup-content color-dark bg-accent"><div class="popup-close hover-accent"><span class="icon-cross"></span></div><div class="popup-center"><dnn:SEARCH runat="server" id="dnnSEARCH427525" CssClass="search"  ShowSite="False" ShowWeb="False"  submit=" " /></div></div></div>
		<dnn:DnnCssInclude runat="server" FilePath="resource/header/search-popup/search-popup.css" PathNameAlias="SkinPath" Priority="318" HtmlAttributesAsString="media:'none',title:'all',onload:'this.media=this.title"  />
		<dnn:DnnJsInclude runat="server" FilePath="resource/header/search-popup/search-popup.js"  ForceProvider ="DnnFormBottomProvider" PathNameAlias="SkinPath" Priority="9" HtmlAttributesAsString="async:'async'"   />	
		</div></div> <div class="header-area area-center header-horizontal  header-horizontal"   id="column-460671"><div class="header-content-wrap"> <div class="logo" id="logo889099"><dnn:LOGO runat="server" id="dnnLOGO889099" cssClass="header-logo" BorderWidth="0" /><dnn:LOGO runat="server" id="floatingLOGO889099" cssClass="floating-header-logo" BorderWidth="0" /></div></div></div> <div class="header-area area-right header-horizontal text-right header-horizontal text-right"   id="column-682201"><div class="header-content-wrap"> <div class="mobile-menu-icon"><span class="dg-menu-anime"><i></i></span></div>
	<div class="mobilemenu-main" id="mobilemenu928270" data-title="Menu"><span class="mobileclose"></span>
	<div class="m-menu">
	<dnn:LEFTGOMENU runat="server" id="MOBILEMENU928270" Effect="HTML"/> 
	</div>
	</div>
	<dnn:DnnCssInclude runat="server" FilePath="resource/header/mobilemenu/mobilemenu.css" PathNameAlias="SkinPath" Priority="317" HtmlAttributesAsString="media:'none',title:'all',onload:'this.media=this.title"  />
	<dnn:DnnJsInclude runat="server" FilePath="resource/header/mobilemenu/mobilemenu.js" ForceProvider ="DnnFormBottomProvider" PathNameAlias="SkinPath" Priority="17" HtmlAttributesAsString="async:'async'"   />	
	</div></div> </div></div> </header></div>