<div class="header-replace header-position"><header class="header_bg header-wrap header-default floating-nav floating-nav-sticky"><div id="megamenuWidthBox" class="container"></div>  <div class="header-center-bg floating-dark-color header-bg-box" data-height="70"  id="headerrow-349356"><div class="container"><div class="header-center header-container-box"> <div class="header-area area-left header-horizontal  pl-30 header-horizontal"   id="column-645135"><div class="header-content-wrap"> <div class="menu-3d-popup-box" id="menu-3d-popup-box390055" data-brushcolor="var(--accent-color2)"><div class="icon hover-accent"><span></span></div><div class="popup-reveal color-dark "></div><div class="menu-3d-popup-main" id="menu-3d-popup-main390055"><div class="menu-3d-popup-close"><span></span></div><div class="container"><div class="popup-top"><div class="logo"><dnn:LOGO runat="server" id="dnnLOGO390055" BorderWidth="0" /></div></div><div class="popup-center"><dnn:LEFTGOMENU runat="server" id="dnnGOMENU390055" Effect="HTML" /></div><div class="popup-bottom"><div class="homepage08-header-text">
<p><b>Email:</b> service.simple@gmail.com</p>
<p><b>Contact:</b> (845) 359-7777</p>
</div></div></div></div></div>
	<dnn:DnnCssInclude runat="server" FilePath="resource/header/menu3dpopup/menu3dpopup.css" PathNameAlias="SkinPath" Priority="322" HtmlAttributesAsString="media:'none',title:'all',onload:'this.media=this.title"  />
	<dnn:DnnJsInclude runat="server" FilePath="resource/header/menu3dpopup/menu3dpopup.js" ForceProvider ="DnnFormBottomProvider" PathNameAlias="SkinPath" Priority="9" HtmlAttributesAsString="async:'async'"   />	
	<div class="logo" id="logo575027"><a href="<%=DotNetNuke.Common.Globals.NavigateURL(PortalSettings.HomeTabId).ToString()%>" title="<%=PortalSettings.PortalName %>"><img src="/Portals/_default/ContentBuilder/minis-page/home08/homepage08-logo.png"  class="header-logo" alt="<%=PortalSettings.PortalName %>" /></a><a href="<%=DotNetNuke.Common.Globals.NavigateURL(PortalSettings.HomeTabId).ToString()%>" title="<%=PortalSettings.PortalName %>"><img src="/Portals/_default/ContentBuilder/minis-page/logo-black.png"  class="floating-header-logo" alt="<%=PortalSettings.PortalName %>"></a></div></div></div> <div class="header-area area-center header-vertical text-right header-vertical text-right"   id="column-930454"><div class="header-content-wrap"> </div></div> <div class="header-area area-right header-horizontal  pr-30 header-horizontal"   id="column-722316"><div class="header-content-wrap"> <div class="dngTextBox"><strong>Contact: (845) 359-7777</strong></div><div class="search-popup-box" id="search-popup-box623472" placeholder="Enter any key words to search"><div class="icon hover-accent"><span class="magnifier"><i></i></span></div><div class="popup-reveal color-dark "></div><div class="popup-content color-dark bg-accent"><div class="popup-close hover-accent"><span class="icon-cross"></span></div><div class="popup-center"><dnn:SEARCH runat="server" id="dnnSEARCH623472" CssClass="search"  ShowSite="False" ShowWeb="False"  submit=" " /></div></div></div>
		<dnn:DnnCssInclude runat="server" FilePath="resource/header/search-popup/search-popup.css" PathNameAlias="SkinPath" Priority="318" HtmlAttributesAsString="media:'none',title:'all',onload:'this.media=this.title"  />
		<dnn:DnnJsInclude runat="server" FilePath="resource/header/search-popup/search-popup.js"  ForceProvider ="DnnFormBottomProvider" PathNameAlias="SkinPath" Priority="9" HtmlAttributesAsString="async:'async'"   />	
		</div></div> </div></div></div>  </header></div><div class="mobile-header-replace"><header class="mobile-header floating-nav"> <div class="header-mobile-bg mobile-header-shadow" id="mobileheader-639685"><div class="header-mobile"> <div class="header-area area-left header-horizontal text-left header-horizontal text-left"   id="column-615625"><div class="header-content-wrap"> <div class="search-popup-box" id="search-popup-box123587" placeholder="Enter any key words to search"><div class="icon hover-accent"><span class="magnifier"><i></i></span></div><div class="popup-reveal color-dark "></div><div class="popup-content color-dark bg-accent"><div class="popup-close hover-accent"><span class="icon-cross"></span></div><div class="popup-center"><dnn:SEARCH runat="server" id="dnnSEARCH123587" CssClass="search"  ShowSite="False" ShowWeb="False"  submit=" " /></div></div></div>
		<dnn:DnnCssInclude runat="server" FilePath="resource/header/search-popup/search-popup.css" PathNameAlias="SkinPath" Priority="318" HtmlAttributesAsString="media:'none',title:'all',onload:'this.media=this.title"  />
		<dnn:DnnJsInclude runat="server" FilePath="resource/header/search-popup/search-popup.js"  ForceProvider ="DnnFormBottomProvider" PathNameAlias="SkinPath" Priority="9" HtmlAttributesAsString="async:'async'"   />	
		</div></div> <div class="header-area area-center header-horizontal  header-horizontal"   id="column-946586"><div class="header-content-wrap"> <div class="logo" id="logo712896"><dnn:LOGO runat="server" id="dnnLOGO712896" cssClass="header-logo floating-header-logo" BorderWidth="0" /></div></div></div> <div class="header-area area-right header-horizontal text-right header-horizontal text-right"   id="column-62191"><div class="header-content-wrap"> <div class="mobile-menu-icon"><span class="dg-menu-anime"><i></i></span></div>
	<div class="mobilemenu-main" id="mobilemenu11098" data-title="Menu"><span class="mobileclose"></span>
	<div class="m-menu">
	<dnn:LEFTGOMENU runat="server" id="MOBILEMENU11098" Effect="HTML"/> 
	</div>
	</div>
	<dnn:DnnCssInclude runat="server" FilePath="resource/header/mobilemenu/mobilemenu.css" PathNameAlias="SkinPath" Priority="317" HtmlAttributesAsString="media:'none',title:'all',onload:'this.media=this.title"  />
	<dnn:DnnJsInclude runat="server" FilePath="resource/header/mobilemenu/mobilemenu.js" ForceProvider ="DnnFormBottomProvider" PathNameAlias="SkinPath" Priority="17" HtmlAttributesAsString="async:'async'"   />	
	</div></div> </div></div> </header></div>